project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R for Ecologists - NAU 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - setup.qmd
      - about.qmd
      - learn.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

