project:
  type: website
  output-dir: docs

website:
  title: "NAU_R_Workshop2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

