---
title: "Schedule"
---

Tuesdays, 9:30-11:00

Physical Sciences 321

### 1. December 10: Why R?

In this workshop, we will walk through an overview of R and why it is so useful for ecologists. During this workshop, the instructors will ensure that everyone has successfully downloaded R and RStudio and completed the setup tasks outlined in the [Setup](https://anamtk.github.io/NAU_R_Workshop2024/setup.html) tab.

[Presentation PDF](https://github.com/anamtk/NAU_R_Workshop2024/blob/main/sessions/Why%20R.pdf)

### 2. December 17: [Getting Started in R and RStudio](https://datacarpentry.github.io/R-ecology-lesson-alternative/introduction-r-rstudio.html)

In this workshop, we will get oriented to R and RStudio and how they work together. We will also talk about file and folder organization that will generally be helful for project management, but make it much easier to work with R programming on your computer. We will also quickly review why ecologists use R for data analysis.

[Live coding script](https://github.com/anamtk/NAU_R_Workshop2024/blob/main/livecoding/01_gettingstarted.R)

### 3. January 7: [Data Visualization with `ggplot2`](https://datacarpentry.github.io/R-ecology-lesson-alternative/visualizing-ggplot.html)

In this workshop, we will learn how to visualize data in R and RStudio using a package called `ggplot2`

[Live coding script](https://github.com/anamtk/NAU_R_Workshop2024/blob/main/livecoding/02_plotsinggplot2.R)

### 4. January 14: [Data Visualization with `ggplot2`](https://datacarpentry.github.io/R-ecology-lesson-alternative/visualizing-ggplot.html) & [Exploring and Understanding Data](https://datacarpentry.github.io/R-ecology-lesson-alternative/how-r-thinks-about-data.html)

In this workshop, we will dive a bit deeper into R and learn how R stores data and how different ways that R stores data can help ecologists working with R.

[Live coding script](https://github.com/anamtk/NAU_R_Workshop2024/blob/main/livecoding/02_plotsinggplot2.R)

::: {.callout-note appearance="minimal"}
## Try it on your own!

Try making your own plot! You can run `str(complete_old)` or `?complete_old` to explore variables you might use in your new plot. Feel free to use variables we have already seen, or some we haven't explored yet.

Here are a couple ideas to get you started:

-   make a histogram of one of the numeric variables

-   try using a different color `scale_`

-   try changing the size of points or thickness of lines in a `geom`

You can explore some plotting option in the [R Graph Gallery](https://r-graph-gallery.com/) or get ideas about types of plots with the [ggplot2 cheat sheet](https://rstudio.github.io/cheatsheets/html/data-visualization.html) (which is also available in RStudio in the `Help` tab on the top of RStudio window).
:::

### 5. February 4: [Exploring and Understanding Data](https://datacarpentry.github.io/R-ecology-lesson-alternative/how-r-thinks-about-data.html) 

In this workshop, we continued to explore how R understands data.

[Live coding script](https://github.com/anamtk/NAU_R_Workshop2024/blob/main/livecoding/03_exploring_data.R)

### 6. February 11: [Exploring and Understanding Data](https://datacarpentry.github.io/R-ecology-lesson-alternative/how-r-thinks-about-data.html) & [Working with Data, Part 2](https://datacarpentry.github.io/R-ecology-lesson-alternative/working-with-data.html)

In this workshop session, we will continue to explore and understand how R looks at data. We will then work on importing data into R. We will then perform common data exploration and cleaning steps and the final step will be to export a "clean" dataset.

[Live coding script available after workshop]()

::: {.callout-note appearance="minimal"}
## Try it on your own!

Using the steps we used to import a dataset in this workshop, try importing one of your own datasets into R. If you don't have your own dataset yet, explore some options at the [Ecological Dataset Wiki](https://ecologicaldata.org/find-data). Explore the data using one or more of the functions we used today (`select`, `filter`, or `mutate`). What did you learn about the data? In a nutshell:

-   use `read_csv` function to import a dataset into R

-   Explore the dataset with one or more of the functions `select`, `filter`, and `mutate`

-   What did you learn about the dataset using these functions that can help you understand and work with your data better?
:::

### 7. March 18: [Exploring and Understanding Data](https://datacarpentry.github.io/R-ecology-lesson-alternative/how-r-thinks-about-data.html)  & [Introduction to Statistics in R](https://anamtk.github.io/stats_workshop/Introduction_to_Statistics.html)

In this workshop, we will continue to explore data in R. We will also learn about how to run statistical tests in R. These will match statistical tests participants will already know how to do in the program JMP from earlier in the RaMP training.

[Live coding script available after workshop]()

### 8. March 25: [Introduction to Statistics in R 2](https://anamtk.github.io/stats_workshop/Introduction_to_Statistics.html)

In this workshop, we will continue to learn about how to run statistical tests in R. These will match statistical tests participants will already know how to do in the program JMP from earlier in the RaMP training.

[Live coding script available after workshop]()

### 9. April 15: Working with Data, Part 3

In this workshop session, participants will continue to import their own datasets into R. We will process and visualize data together during the session and instructors will be available to troubleshoot issues with data in R. We will also explore statistical analyses with participant datasets.

[Live coding script available after workshop]()
